# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - localhost:9095

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'Demo UI'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'Demo API'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9092']

  - job_name: 'Prometheus'
    static_configs:
      - targets: ['localhost:9090']


